"""Defines global parameters for application."""

DATA_PATH = './data'

COLORS = {
    "red": (255, 0, 0),
    "green": (0, 255, 0),
    "blue": (0, 0, 255),
    "white": (255, 255, 255),
    "black": (0, 0, 0)
}

BACKGROUND_COLOR = COLORS["black"]
HEALTH_BAR_COLOR = COLORS["red"]
TEXT_COLOR = COLORS["white"]
SURFACE_COLOR = COLORS["black"]

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600

HEALTH_BAR_WIDTH = 100
HEALTH_BAR_HEIGHT = 12
HEALTH_BAR_BORDER = 4

PLAYER_HP = 100

ALIEN_HP = 1
ALIEN_SPEED = 0.5
ALIEN_GROUP_ROWS = 5
ALIEN_GROUP_COLUMNS = 11
ALIEN_GROUP_SPACING = 0.75
ALIEN_GROUP_COOLDOWN = 800
ALIEN_SCORE = 10

BUILDING_HP = 100
BUILDING_SCORE = 10

BULLET_SPEED = 5
BULLET_DAMAGE = 10
EXPLOSION_RADIUS = 5

DIFFICULTY_SPEED = 0.02
DIFFICULTY_COOLDOWN = 3

NAME_LENGTH = 3
LEADERBOARD_LENGTH = 6

UP, DOWN, LEFT, RIGHT = range(4)
